---
- name: Setup cluster foundations
  hosts: golden_image
  become: true
  vars:
    ansible_user: ubuntu

  roles:
    - role: server_golden_image
      vars:
        
        github_users:
          - gabepsilva


- name: Setup on-prem vpn server
- hosts: onprem_vpn_server
  become: true
  roles:
    - wireguard
  vars:
    sudo_user: ubuntu
    wireguard_address: "10.0.0.1/24"
    wireguard_private_key: "your_private_key_here"
    wireguard_peers:
      - public_key: "peer1_public_key"
        allowed_ips: "10.0.0.2/32"