---
all:
  children:
    k8s:
      children:
        k8s_golden_image: # optional
          hosts:
            k8s-golden-net1.i.psilva.org:
              ansible_host: k8s-golden-net1.i.psilva.org
            k8s-golden-net2.i.psilva.org:
              ansible_host: k8s-golden-net2.i.psilva.org
        k8s_servers:
          children:
            k8s_masters:
              hosts:
                k8s-master1.i.psilva.org:
                  ansible_host: k8s-master1.i.psilva.org
                k8s-master2.i.psilva.org:
                  ansible_host: k8s-master2.i.psilva.org
                k8s-master3.i.psilva.org:
                  ansible_host: k8s-master3.i.psilva.org
            k8s_nodes:
              children:
                k8s_nodes_acpu:
                  hosts:
                    k8s-node1.i.psilva.org:
                      ansible_host: k8s-node1.i.psilva.org
                    k8s-node2.i.psilva.org:
                      ansible_host: k8s-node2.i.psilva.org
                    k8s-node3.i.psilva.org:
                      ansible_host: k8s-node3.i.psilva.org
                k8s_nodes_agpu:
                    hosts:
                      k8s-node4-agpu.i.psilva.org:
                        ansible_host: k8s-node4-agpu.i.psilva.org
                k8s_nodes_gaws:
                  hosts:
                    ec2-18-226-82-155.us-east-2.compute.amazonaws.com:
                      ansible_host: ec2-18-226-82-155.us-east-2.compute.amazonaws.com
    vpn:
      children:
        vpn_golden_image:
          hosts:
            vpn-golden-net1.i.psilva.org:
              ansible_host: vpn-golden-net1.i.psilva.org
            vpn-golden-net2.i.psilva.org:
              ansible_host: vpn-golden-net2.i.psilva.org
        vpn_servers:
          children:
            vpn_onprem1:
              hosts:
                vpn-onprem1.i.psilva.org:
                  ansible_host: vpn-onprem1.i.psilva.org
            vpn_onprem2:
              hosts:
                vpn-onprem2.i.psilva.org:
                  ansible_host: vpn-onprem2.i.psilva.org
