---
all:
  children:
    k8s:
      children:
        golden_image:
          hosts:
            k8s-golden.i.psilva.org:
              ansible_host: k8s-golden.i.psilva.org
        k8s_servers:
          children:
            k8s_masters:
              hosts:
                k8s-master1.i.psilva.org:
                  ansible_host: k8s-master1.i.psilva.org
                k8s-master2.i.psilva.org:
                  ansible_host: k8s-master2.i.psilva.org
                k8s-master3.i.psilva.org:
                  ansible_host: k8s-master3.i.psilva.org
            k8s_nodes:
              children:
                k8s_nodes_acpu:
                  hosts:
                    k8s-node1.i.psilva.org:
                      ansible_host: k8s-node1.i.psilva.org
                    k8s-node2.i.psilva.org:
                      ansible_host: k8s-node2.i.psilva.org
                    k8s-node3.i.psilva.org:
                      ansible_host: k8s-node3.i.psilva.org
                k8s_nodes_agpu:
                    hosts:
                      k8s-node4-agpu.i.psilva.org:
                        ansible_host: k8s-node4-agpu.i.psilva.org

