---
- name: Setup VPN Server foundations
  hosts: vpn_golden_image
  become: true
  vars:
    ansible_user: ubuntu

  roles:
    - role: server_golden_image
      vars:
        sudo_user: ubuntu
        github_users:
          - gabepsilva
    